name: base
channels:
  - r
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - _libgcc_mutex=0.1
  - _r-mutex=1.0.1
  - alabaster=0.7.12
  - anaconda=2019.10
  - anaconda-clean=1.1.0
  - anaconda-client=1.7.2
  - anaconda-navigator=1.9.7
  - anaconda-project=0.8.3
  - asn1crypto=1.0.1
  - astroid=2.3.1
  - astropy=3.2.2
  - atomicwrites=1.3.0
  - attrs=19.2.0
  - babel=2.7.0
  - backcall=0.1.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - backports.os=0.1.1
  - backports.shutil_get_terminal_size=1.0.0
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - beautifulsoup4=4.8.0
  - bedtools=2.29.0
  - binutils_impl_linux-64=2.33.1
  - binutils_linux-64=2.33.1
  - biopython=1.74
  - bitarray=1.0.1
  - bkcharts=0.2
  - blas=1.0
  - bleach=3.1.0
  - blosc=1.16.3
  - bokeh=1.3.4
  - boto=2.49.0
  - bottleneck=1.2.1
  - bowtie2=2.2.5
  - bqplot=0.12.1
  - bwidget=1.9.13
  - bzip2=1.0.8
  - ca-certificates=2019.8.28
  - cairo=1.14.12
  - cd-hit=4.8.1
  - certifi=2019.9.11
  - cffi=1.12.3
  - chardet=3.0.4
  - click=7.0
  - cloudpickle=1.2.2
  - clyent=1.2.2
  - colorama=0.4.1
  - conda=4.7.12
  - conda-build=3.18.9
  - conda-env=2.6.0
  - conda-package-handling=1.6.0
  - conda-verify=3.4.2
  - contextlib2=0.6.0
  - cryptography=2.7
  - curl=7.65.3
  - cycler=0.10.0
  - cython=0.29.13
  - cytoolz=0.10.0
  - dask=2.5.2
  - dask-core=2.5.2
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.6.0
  - distributed=2.5.2
  - docutils=0.15.2
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - expat=2.2.6
  - fastcache=1.1.0
  - filelock=3.0.12
  - flask=1.1.1
  - fontconfig=2.13.0
  - freetype=2.9.1
  - fribidi=1.0.5
  - fsspec=0.5.2
  - future=0.18.2
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - get_terminal_size=1.0.0
  - gevent=1.4.0
  - gfortran_impl_linux-64=7.3.0
  - gfortran_linux-64=7.3.0
  - git=2.23.0
  - glib=2.56.2
  - glob2=0.7
  - gmp=6.1.2
  - gmpy2=2.0.8
  - graphite2=1.3.13
  - greenlet=0.4.15
  - gsl=2.4
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - h5py=2.9.0
  - harfbuzz=1.8.8
  - hdf5=1.10.4
  - heapdict=1.0.1
  - html5lib=1.0.1
  - htslib=1.9
  - icu=58.2
  - idna=2.8
  - imageio=2.6.0
  - imagesize=1.1.0
  - importlib_metadata=0.23
  - intel-openmp=2019.4
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=4.3.21
  - itsdangerous=1.1.0
  - jbig=2.1
  - jdcal=1.4.1
  - jedi=0.15.1
  - jeepney=0.4.1
  - jinja2=2.10.3
  - joblib=0.13.2
  - jpeg=9b
  - json5=0.8.5
  - jsonschema=3.0.2
  - jupyter=1.0.0
  - jupyter_client=5.3.3
  - jupyter_console=6.0.0
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_core=4.5.0
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.4
  - jupyter_nbextensions_configurator=0.4.1
  - jupyterlab=1.1.4
  - jupyterlab_server=1.0.6
  - keyring=18.0.0
  - kiwisolver=1.1.0
  - krb5=1.16.1
  - lazy-object-proxy=1.4.2
  - ld_impl_linux-64=2.33.1
  - libarchive=3.3.3
  - libcurl=7.65.3
  - libdeflate=1.3
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - liblief=0.9.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libssh2=1.8.2
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libtool=2.4.6
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - libxslt=1.1.33
  - llvm-openmp=8.0.1
  - llvmlite=0.29.0
  - locket=0.2.0
  - lxml=4.4.1
  - lz4-c=1.8.1.2
  - lzo=2.10
  - make=4.2.1
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.1.0
  - mock=3.0.5
  - more-itertools=7.2.0
  - mpc=1.1.0
  - mpfr=4.0.1
  - mpmath=1.1.0
  - msgpack-python=0.6.1
  - multipledispatch=0.6.0
  - navigator-updater=0.2.1
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - ncurses=6.1
  - networkx=2.3
  - nltk=3.4.5
  - nodejs=11.14.0
  - nose=1.3.7
  - notebook=6.0.1
  - numba=0.45.1
  - numexpr=2.7.0
  - numpy=1.17.2
  - numpy-base=1.17.2
  - numpydoc=0.9.1
  - olefile=0.46
  - openmp=8.0.1
  - openpyxl=3.0.0
  - openssl=1.1.1d
  - packaging=19.2
  - pandas=0.25.1
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.5.1
  - partd=1.0.0
  - patchelf=0.9
  - path.py=12.0.1
  - pathlib2=2.3.5
  - patsy=0.5.1
  - pcre=8.43
  - pep8=1.7.1
  - perl=5.26.2
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.2.0
  - pip=19.2.3
  - pixman=0.38.0
  - pkginfo=1.5.0.1
  - pluggy=0.13.0
  - ply=3.11
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - psutil=5.6.3
  - ptyprocess=0.6.0
  - py=1.8.0
  - py-lief=0.9.0
  - pycodestyle=2.5.0
  - pycosat=0.6.3
  - pycparser=2.19
  - pycrypto=2.6.1
  - pycurl=7.43.0.3
  - pyflakes=2.1.1
  - pygments=2.4.2
  - pylint=2.4.2
  - pyodbc=4.0.27
  - pyopenssl=19.0.0
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pyrsistent=0.15.4
  - pysocks=1.7.1
  - pytables=3.5.2
  - pytest=5.2.1
  - pytest-arraydiff=0.3
  - pytest-astropy=0.5.0
  - pytest-doctestplus=0.4.0
  - pytest-openfiles=0.4.0
  - pytest-remotedata=0.3.2
  - python=3.7.4
  - python-dateutil=2.8.0
  - python-libarchive-c=2.8
  - pytz=2019.3
  - pywavelets=1.0.3
  - pyyaml=5.1.2
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtawesome=0.6.0
  - qtconsole=4.5.5
  - qtpy=1.9.0
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.1.5
  - r-base=3.5.1
  - r-base64enc=0.1_3
  - r-bh=1.69.0_1
  - r-bit=1.1_14
  - r-bit64=0.9_7
  - r-blob=1.2.0
  - r-boot=1.3_23
  - r-broom=0.5.2
  - r-callr=3.3.2
  - r-caret=6.0_84
  - r-cellranger=1.1.0
  - r-class=7.3_15
  - r-cli=1.1.0
  - r-clipr=0.7.0
  - r-cluster=2.1.0
  - r-codetools=0.2_16
  - r-colorspace=1.4_1
  - r-crayon=1.3.4
  - r-curl=4.2
  - r-data.table=1.12.6
  - r-dbi=1.0.0
  - r-dbplyr=1.4.2
  - r-digest=0.6.22
  - r-dplyr=0.8.3
  - r-ellipsis=0.3.0
  - r-essentials=3.5.1
  - r-evaluate=0.14
  - r-fansi=0.4.0
  - r-farver=2.0.1
  - r-fastmap=1.0.1
  - r-forcats=0.4.0
  - r-foreach=1.4.7
  - r-foreign=0.8_72
  - r-formatr=1.7
  - r-fs=1.3.1
  - r-generics=0.0.2
  - r-ggplot2=3.2.1
  - r-gistr=0.4.2
  - r-glmnet=2.0_18
  - r-glue=1.3.1
  - r-gower=0.2.1
  - r-gtable=0.3.0
  - r-haven=2.2.0
  - r-hexbin=1.28.0
  - r-highr=0.8
  - r-hms=0.5.2
  - r-htmltools=0.4.0
  - r-htmlwidgets=1.5.1
  - r-httpuv=1.5.2
  - r-httr=1.4.1
  - r-ipred=0.9_9
  - r-irdisplay=0.7
  - r-irkernel=1.0.2
  - r-iterators=1.0.12
  - r-jsonlite=1.6
  - r-kernsmooth=2.23_15
  - r-knitr=1.26
  - r-labeling=0.3
  - r-later=1.0.0
  - r-lattice=0.20_38
  - r-lava=1.6.6
  - r-lazyeval=0.2.2
  - r-lifecycle=0.1.0
  - r-lubridate=1.7.4
  - r-magrittr=1.5
  - r-maps=3.3.0
  - r-markdown=1.1
  - r-mass=7.3_51.4
  - r-matrix=1.2_17
  - r-memoise=1.1.0
  - r-mgcv=1.8_29
  - r-mime=0.7
  - r-modelmetrics=1.2.2
  - r-modelr=0.1.5
  - r-munsell=0.5.0
  - r-nlme=3.1_141
  - r-nnet=7.3_12
  - r-numderiv=2016.8_1.1
  - r-openssl=1.4.1
  - r-pbdzmq=0.3_3
  - r-permute=0.9_5
  - r-pheatmap=1.0.12
  - r-pillar=1.4.2
  - r-pkgconfig=2.0.3
  - r-plogr=0.2.0
  - r-plyr=1.8.4
  - r-prettyunits=1.0.2
  - r-processx=3.4.1
  - r-prodlim=2019.11.13
  - r-progress=1.2.2
  - r-promises=1.1.0
  - r-pryr=0.1.4
  - r-ps=1.3.0
  - r-purrr=0.3.3
  - r-quantmod=0.4_15
  - r-r6=2.4.1
  - r-randomforest=4.6_14
  - r-rbokeh=0.5.0
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.3
  - r-readr=1.3.1
  - r-readxl=1.3.1
  - r-recipes=0.1.7
  - r-recommended=3.5.1
  - r-rematch=1.0.1
  - r-repr=1.0.1
  - r-reprex=0.3.0
  - r-reshape2=1.4.3
  - r-rlang=0.4.1
  - r-rmarkdown=1.17
  - r-rpart=4.1_15
  - r-rsqlite=2.1.1
  - r-rstudioapi=0.10
  - r-rvest=0.3.5
  - r-scales=1.1.0
  - r-selectr=0.4_1
  - r-shiny=1.4.0
  - r-sourcetools=0.1.7
  - r-spatial=7.3_11
  - r-squarem=2017.10_1
  - r-stringi=1.4.3
  - r-stringr=1.4.0
  - r-survival=2.44_1.1
  - r-sys=3.3
  - r-tibble=2.1.3
  - r-tidyr=1.0.0
  - r-tidyselect=0.2.5
  - r-tidyverse=1.3.0
  - r-timedate=3043.102
  - r-tinytex=0.17
  - r-ttr=0.23_5
  - r-utf8=1.1.4
  - r-uuid=0.1_2
  - r-vctrs=0.2.0
  - r-vegan=2.5_6
  - r-viridislite=0.3.0
  - r-whisker=0.4
  - r-withr=2.1.2
  - r-xfun=0.11
  - r-xml2=1.2.2
  - r-xtable=1.8_4
  - r-xts=0.11_2
  - r-yaml=2.2.0
  - r-zeallot=0.1.0
  - r-zoo=1.8_6
  - readline=7.0
  - requests=2.22.0
  - ripgrep=0.10.0
  - rope=0.14.0
  - ruamel_yaml=0.15.46
  - samtools=1.9
  - scikit-image=0.15.0
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - seaborn=0.9.0
  - secretstorage=3.1.1
  - send2trash=1.5.0
  - setuptools=41.4.0
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - sip=4.19.8
  - six=1.12.0
  - snappy=1.1.7
  - snowballstemmer=2.0.0
  - sortedcollections=1.1.2
  - sortedcontainers=2.1.0
  - soupsieve=1.9.3
  - sphinx=2.2.0
  - sphinxcontrib=1.0
  - sphinxcontrib-applehelp=1.0.1
  - sphinxcontrib-devhelp=1.0.1
  - sphinxcontrib-htmlhelp=1.0.2
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.2
  - sphinxcontrib-serializinghtml=1.1.3
  - sphinxcontrib-websupport=1.1.2
  - spyder=3.3.6
  - spyder-kernels=0.5.2
  - sqlalchemy=1.3.9
  - sqlite=3.30.0
  - statsmodels=0.10.1
  - sympy=1.4
  - tbb=2019.4
  - tblib=1.4.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - tktable=2.10
  - toolz=0.10.0
  - tornado=6.0.3
  - tqdm=4.36.1
  - traitlets=4.3.3
  - unicodecsv=0.14.1
  - unixodbc=2.3.7
  - urllib3=1.24.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.16.0
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - wurlitzer=1.0.3
  - xlrd=1.2.0
  - xlsxwriter=1.2.1
  - xlwt=1.3.0
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zict=1.0.0
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - docker==4.1.0
    - docopt==0.6.2
    - escapism==1.0.0
    - jupyter-repo2docker==0.10.0
    - nbinteract==0.2.4
    - python-json-logger==0.1.11
    - ruamel-yaml==0.16.5
    - ruamel-yaml-clib==0.2.0
    - semver==2.9.0
    - toml==0.10.0
    - traittypes==0.2.1
    - websocket-client==0.56.0
prefix: /mnt/home/dooleys1/bin/anaconda3
